.\" Hint for emacs: -*- nroff -*-
.\" This is the manual page for atrogue. To open it in a _human-readable_ form,
.\" try a command like "man atrogue" or "man ./atrogue.6".
.\"
.\" atrogue/docu/atrogue.6 - manual page
.\" This file is part of atrogue, a "Roguelike game" created by Arne Thomassen;
.\" atrogue is basically released under certain versions of the GNU General
.\" Public License and WITHOUT ANY WARRANTY.
.\" Read the file COPYING for license details, README for game information.
.\" Copyright (C) 2001-2010 Arne Thomassen <arne@arne-thomassen.de>
.TH atrogue 6 "22 February 2010" "atrogue 0.3.0" "atrogue manual"
.SH NAME
atrogue \- a Rogue-like game for text environments
.\" .SH SYNOPSIS
.\" .B atrogue
.SH DESCRIPTION
atrogue is a "Rogue-like game" - a certain kind of turn-based, single-player dungeon exploration adventure - for text terminals on computers with Unix-like operating systems.
.P
A short gameplay description: you try to find a way through a magic dungeon with nasty traps, in search of the Amulet of Yendor which is concealed somewhere deep in the dungeon. You fight against hostile creatures with magic actions and weapons and try to escape the dungeon alive and with lots of gold. - One of the goals of playing atrogue is to discover all the things that might happen on your own, so we don't reveal everything here. :-)
.P
Since many things in this game depend on chance, you get a different dungeon each time you play it.
.P
The most recent version of atrogue is available on the project home page <http://atrogue.sourceforge.net/>.
.\" .SH "EXIT STATUS"
.SH OPTIONS
atrogue provides many compile-time options and command-line options, e.g. for optional color support, a selectable gameplay difficulty and a variable dungeon size. Extensive documentation about these can be found in
.IR atrogue/docu/config.html " and " atrogue/docu/arg.html " in the release package."
.SH LICENSE
atrogue is basically released under certain versions of the GNU General Public License and WITHOUT ANY WARRANTY. Read the file
.I atrogue/COPYING
(in the release package) for license details.
.SH BUGS
This program has no bugs. no bugs. no bugs. no *WHAP* thank you.
.\" Found in frotz(6) :-)
Seriously: a list of known bugs and problems is available on the project web pages. Information about how to report bugs can be found there and in the file
.I atrogue/README
in the release package.
.SH AUTHOR
Arne Thomassen <arne@arne-thomassen.de>
.SH "SEE ALSO"
.BR rogue (6)
